#!/bin/bash

cd /tmp

CANNOT_INSTALL=(openafs-modules-dkms apt-show-versions memtest86)
export DEBIAN_FRONTEND=noninteractive

apt update -qqq

apt purge linux-image* linux-headers* -yqqq

apt upgrade -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -yqqq

apt install ca-certificates apt-listchanges -yqqq

cp -r apt /etc

apt update

#E: Unable to locate package libpbspro
#E: Package 'libssl1.0.0' has no installation candidate

CANNOT_INSTALL=(${CANNOT_INSTALL[*]} $(apt install -s `cat packages_file` 2>&1 | grep -Po "(E: Unable to locate package |E: Package ')\K[^&']+"))

for i in ${CANNOT_INSTALL[*]}; do sed -i "s/^$i$//" packages_file; done

apt install -y `cat packages_file` ./openafs-modules-*

cp krb5.conf /etc
cp idmapd.conf /etc
cp -r auto.master.d /etc
#cp auto.meta-nfs /etc
cp -r storage /
cp -r openafs /etc
cp -r cvmfs /etc
cp -r csh /etc
cp -r profile.d /etc
cp -r packages /
cp singularity.conf /etc/singularity/singularity.conf

ln -sfr /bin/bash /bin/sh

sed "s/OPTIONS=AUTOMATIC/OPTIONS=\"-rxmaxmtu 1380\"/" /etc/openafs/afs.conf -i
echo 'install nfs /usr/sbin/modprobe --ignore-install nfs nfs4_unique_id=$(/usr/bin/cat /etc/nfsid 2>/dev/null || /usr/bin/cat /proc/sys/kernel/random/uuid | /usr/bin/tee /etc/nfsid)' > /etc/modprobe.d/nfs.conf

while read a b c; do if [[ "$b" ]] && [[ ! "$b" =~ vers ]]; then echo "$a $b,vers=4.0 $c"; else echo "$a $b $c"; fi; done < /tmp/auto.meta-nfs\
> /etc/auto.meta-nfs

echo 'RPCGSSDARGS=-n' >> /etc/default/nfs-common
mkdir -p /etc/systemd/system/rpc-gssd.service.d/
echo '[Unit]
ConditionPathExists=
' > /etc/systemd/system/rpc-gssd.service.d/override.conf

rm -r /var/lib/apt/lists/*
rm /etc/ssh/ssh_host_*

apt-get clean

mkdir -p /afs /auto /scratch /scratch.ssd /cvmfs

ln -sf /afs/ics.muni.cz/software /software
