#!/bin/bash

# Put this to /etc/cron.daily

WORKDIR=/root/debian-workernode/buster
PACKAGES_FILE=${WORKDIR}/packages_file

mkdir -p ${WORKDIR}

cd ${WORKDIR}

touch ${PACKAGES_FILE}
dpkg -l | grep -Po "ii\s+\K[^\s:]+" > ${PACKAGES_FILE}

rm -rf auto.master.d storage apt openafs

cp /etc/krb5.conf .
cp /etc/idmapd.conf .
cp -ar /etc/auto.master.d .
cp /etc/auto.meta-nfs .
cp -ar /storage .
cp -ar /etc/apt .
cp -ar /etc/openafs .

m-a a-b openafs > /dev/null 2>&1

cp /usr/src/openafs-modules-`uname -r`_1.8.6-1+zs2+`uname -v | grep -Po "Debian \K[^ ]+"`_amd64.deb .

git update-index --refresh > /dev/null
if ! git diff-index --quiet HEAD --; then
    echo delej
    #git add .
    #git commit -am "Some packages or files changed `date`"
    #git push origin devel
fi
